"""add acrive attribute in user

Revision ID: 168ecd2e5b0d
Revises: 4b1f23bf4ccc
Create Date: 2024-11-13 19:25:20.315500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168ecd2e5b0d'
down_revision = '4b1f23bf4ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
